"""
state_schema.py

This file defines the single, authoritative data structure for the
CubeSat's real-time state.

This Pydantic model is the "data contract" that is:
1.  Calculated by the `SimulationKernel` on every tick.
2.  Broadcast by the `WebSocketServer` to all frontend clients.
"""
from __future__ import annotations
from pydantic import BaseModel, Field
from typing import List, Tuple, Literal
from datetime import datetime, timezone
from enum import Enum

# --- Alerting Schemas ---
class Alert(BaseModel):
    """A structured alert message."""
    level: Literal['INFO', 'WARNING', 'CRITICAL'] = Field(..., description="Severity of the alert")
    timestamp: datetime = Field(default_factory=datetime.now(timezone.utc), description="Time the alert was generated")
    message: str = Field(..., description="A human-readable alert message")
    source: str = Field(..., description="The subsystem that generated the alert (e.g., 'PowerSystem', 'ADCS')")

# --- Sub-system State Schemas ---

class OrbitalState(BaseModel):
    """Defines the satellite's position and motion in space."""
    timestamp: datetime = Field(default_factory=datetime.now(timezone.utc), description="Simulation time for this state packet (UTC)")
    position: List[float] = Field(default=[0.0, 0.0, 0.0], description="Position vector (x, y, z) in ECEF or a similar frame (km)")
    velocity: List[float] = Field(default=[0.0, 0.0, 0.0], description="Velocity vector (vx, vy, vz) (km/s)")

class AttitudeState(BaseModel):
    """Defines the satellite's orientation (pointing)."""
    q: List[float] = Field(default=[1.0, 0.0, 0.0, 0.0], description="Attitude quaternion (w, x, y, z) from body to inertial frame")
    omega: List[float] = Field(default=[0.0, 0.0, 0.0], description="Angular velocity vector (wx, wy, wz) in body frame (rad/s)")
    pointing_error_deg: float = Field(0.0, description="Calculated pointing error from target (degrees)")

class HardwareState(BaseModel):
    """Defines the emulated state of on-board hardware constraints."""
    power_level_wh: float = Field(100.0, description="Current battery charge in Watt-hours")
    power_draw_mw: float = Field(0.0, description="Total power draw of all subsystems at this instant (mW)")
    power_generation_mw: float = Field(0.0, description="Power being generated by solar panels (mW)")
    cpu_load_percent: float = Field(0.0, description="Emulated CPU load")
    memory_usage_kb: float = Field(0.0, description="Emulated RAM usage")

class TaskState(BaseModel):
    """Defines the state of the onboard computer's task queue."""
    current_task: str = Field("Idle", description="The task currently being processed")
    task_queue: List[str] = Field(default=[], description="List of tasks waiting to be run")

# --- Main State Schema ---

class SatelliteState(BaseModel):
    """
    The main, top-level state object that is broadcast to the frontend.
    It composes all other sub-states.
    """
    orbit: OrbitalState = Field(default_factory=OrbitalState)
    attitude: AttitudeState = Field(default_factory=AttitudeState)
    hardware: HardwareState = Field(default_factory=HardwareState)
    tasks: TaskState = Field(default_factory=TaskState)
    
    alerts: List[Alert] = Field(default=[], description="List of all active system alerts")

